name: .NET

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 10.0.x
    - run: dotnet build --configuration Release --property:Version=1.0.${{ github.run_number }}
    - run: 7z a -tzip VATWorksheet.zip ./bin/Release/net10.0/*
    - uses: aws-actions/configure-aws-credentials@v6
      with:
        aws-region: ap-southeast-1
        role-to-assume: arn:aws:iam::428708741879:role/GithubOIDC
    - run: aws lambda update-function-code --region ap-southeast-1 --function-name VATWorksheet --zip-file fileb://VATWorksheet.zip --publish
    - run: aws cloudfront create-invalidation-for-distribution-tenant --id dt_3GQAPVb5gw0VCflsHfnfcmS6LSN --invalidation-batch '{"Paths":{"Quantity":1,"Items":["/*"]},"CallerReference":"${{ github.run_number }}"}'
